#!/bin/sh
sudo systemctl stop secure-tunnel@aliyun.service
sudo systemctl disable secure-tunnel@aliyun.service
sudo systemctl daemon-reload
sudo cp secure-tunnel@.service /etc/systemd/system/
sudo cp secure-tunnel@aliyun /etc/default/
sudo systemctl start secure-tunnel@aliyun.service
sudo systemctl enable secure-tunnel@aliyun.service
sudo systemctl status secure-tunnel@aliyun.service
